const data = {
  products: [
    {
      name: 'Adidas Slim Camisa',
      slug: 'adidas-fit-shirt',
      category: 'Camisas',
      image: '/images/p1.jpg',
      price: 50,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Productos de calidad',
    },
    {
      name: 'Nike Slim Camisa',
      slug: 'nike-fit-shirt',
      category: 'Camisas',
      image: '/images/p2.jpg',
      price: 60,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 10,
      description: 'Productos de calidad',
    },
    {
      name: 'Lacoste Slim Camisa',
      slug: 'lacoste-fit-shirt',
      category: 'Camisas',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 20,
      brand: 'Lacoste',
      rating: 4.0,
      numReviews: 10,
      description: 'Productos de calidad',
    },
    {
      name: 'HugoBoss Slim Camisa',
      slug: 'hugoboss-fit-shirt',
      category: 'Camisas',
      image: '/images/p4.jpg',
      price: 350,
      countInStock: 5,
      brand: 'Hugo Boss',
      rating: 4.0,
      numReviews: 10,
      description: 'Productos de calidad',
    },
  ],
};

export default data;
